name: Build current macOS Main Branch

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Teacher install dependencies
      working-directory: ./teacher
      run: |
        pip install setuptools
        npm install
        mkdir dist
    - name: Teacher build
      working-directory: ./teacher
      run: npm run build:mac
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: teacher-current-main-macos
        path: |
          ./release/
          !./release/**/mac
          !./release/**/mac-arm64
        retention-days: 3
    - name: Student install dependencies
      working-directory: ./student
      run: |
        npm install
        mkdir dist
    - name: Student build
      working-directory: ./student
      run: npm run build:mac
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: student-current-main-macos
        path: |
          ./release/
          !./release/**/mac
          !./release/**/mac-arm64
        retention-days: 3