
name: Build current Linux Main Branch

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Teacher cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./teacher/.npm
          ./teacher/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./teacher/package-lock.json') }}
    - name: Teacher install dependencies
      working-directory: ./teacher
      run: npm install
    - name: Teacher build
      working-directory: ./teacher
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: teacher-current-main-linux
        path: |
          ./release/
          !./release/**/linux-unpacked
        retention-days: 1
    - name: Student cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./student/.npm
          ./student/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('./student/package-lock.json') }}
    - name: Student install dependencies
      working-directory: ./student
      run: npm install
    - name: Student build
      working-directory: ./student
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: student-current-main-linux
        path: |
          ./release/
          !./release/**/linux-unpacked
        retention-days: 1

