name: Build current macOS Main Branch

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Teacher cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./teacher/.npm
          ./teacher/node_modules
        key: ${{ runner.os }}-node-s-${{ hashFiles('./teacher/**/package-lock.json') }}
    - name: Teacher install dependencies
      working-directory: ./teacher
      run: |
        npm install
        mkdir dist
    - name: Teacher build
      working-directory: ./teacher
      run: npm run build:mac
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: teacher-current-main-macos
    #     path: |
    #       ./release/
    #       !./release/**/*.blockmap
    #       !./release/**/*.yml          
    #       !./release/**/mac
    #       !./release/**/mac-arm64
    #     retention-days: 3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Wähle hier eine Python-Version < 3.12, z.B. 3.10 oder 3.9
        # Optional: cache: 'pip' # Kann das Caching für Python-Pakete aktivieren
    - name: Student cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./student/.npm
          ./student/node_modules
        key: ${{ runner.os }}-node-s-${{ hashFiles('./student/**/package-lock.json') }}
    - name: Student install dependencies
      working-directory: ./student
      run: |
        npm install
        mkdir dist
    - name: Student build
      working-directory: ./student
      run: npm run build:mac
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: student-teacher-current-main-macos
        path: |
          ./release/
          !./release/**/*.blockmap
          !./release/**/*.yml
          !./release/**/mac
          !./release/**/mac-arm64
        retention-days: 5